PKGDIR          ?= ..
L4DIR           ?= $(PKGDIR)/../..

TARGET                   = ex_clntsrv-server
SRC_CC_ex_clntsrv-server = server.cc 
REQUIRES_LIBS            = cxx_libc_io cxx_io

include $(L4DIR)/mk/prog.mk

